// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqnKd7y0YEOSV-ozFQnYrr0S-9DW1IPSc',
    appId: '1:581206120285:web:8042ef799290e4e713fab4',
    messagingSenderId: '581206120285',
    projectId: 'homework-f64e4',
    authDomain: 'homework-f64e4.firebaseapp.com',
    storageBucket: 'homework-f64e4.firebasestorage.app',
    measurementId: 'G-FRRDD7TFL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdO1aLr31IttkiauHJkh0pAJR30n_z_Ig',
    appId: '1:581206120285:android:76faed659be4e14613fab4',
    messagingSenderId: '581206120285',
    projectId: 'homework-f64e4',
    storageBucket: 'homework-f64e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYFRqlyIHxZS15CtNFK6-ulhwUyu1g3p4',
    appId: '1:581206120285:ios:fc117aa5be7dda4513fab4',
    messagingSenderId: '581206120285',
    projectId: 'homework-f64e4',
    storageBucket: 'homework-f64e4.firebasestorage.app',
    androidClientId: '581206120285-cf8le67tip9p7qliqi6kli3c845sa71l.apps.googleusercontent.com',
    iosClientId: '581206120285-ho2dkre16isj1jti1tljfd1oervit58v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterClassroomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYFRqlyIHxZS15CtNFK6-ulhwUyu1g3p4',
    appId: '1:581206120285:ios:fc117aa5be7dda4513fab4',
    messagingSenderId: '581206120285',
    projectId: 'homework-f64e4',
    storageBucket: 'homework-f64e4.firebasestorage.app',
    androidClientId: '581206120285-cf8le67tip9p7qliqi6kli3c845sa71l.apps.googleusercontent.com',
    iosClientId: '581206120285-ho2dkre16isj1jti1tljfd1oervit58v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterClassroomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqnKd7y0YEOSV-ozFQnYrr0S-9DW1IPSc',
    appId: '1:581206120285:web:6fa29bc52c8cb8ad13fab4',
    messagingSenderId: '581206120285',
    projectId: 'homework-f64e4',
    authDomain: 'homework-f64e4.firebaseapp.com',
    storageBucket: 'homework-f64e4.firebasestorage.app',
    measurementId: 'G-69J5MEBQ4B',
  );
}
